### ISSUE TITLE
Bot cant find the Channel anymore

### ISSUE THREAD

**Issue by TrueMB** [Spicord/Spicord#16]
Hello!

I programmed a plugin with yours as an API. Everything worked well! But today it seems to cant remember the Discord channel anymore. I checked the id multiple times and it is definitly correct. Also the bot got administrator rights and always worked! I tried changing the sec key and rejoining the bot to the discord Server. It seems that BanAnnouncer got the same problem.

Is that a general problem and will be gone sooner or later? Or is it maybe a know Issue?

Thank you in Advance!

EDIT: With "cant find the channel" I mean the #getJDA().getChannelbyId() methode.

**Comment by OopsieWoopsie** [comment]
Hi, I have also been experiencing issues with JDA today, as the Discord Gateway version 6 got discontinued.
I just want to let you know that I'm already working into this.

**Comment by OopsieWoopsie** [comment]
Fixed. https://github.com/Spicord/Spicord/releases/tag/3.1.1

**Comment by TrueMB** [comment]
Thanks for the fast work! But now I got following error:

`07:31:20 [INFO] [Spicord] [JDA:WebSocketClient] Connected to WebSocket
07:31:20 [WARNING] [Spicord] [JDA:WebSocketClient] WebSocket connection closed with unknown meaning for close-code 4014
07:31:20 [SEVERE] [Spicord] [JDA:WebSocketClient] Encountered IDENTIFY Rate Limit!
`

Any advice?

**Comment by OopsieWoopsie** [comment]
Read the first lines on the SpigotMC post https://www.spigotmc.org/resources/spicord.64918/

**Comment by TrueMB** [comment]
I dont know how i missed them after looking multiple time careful for informations. But thank you very much again!
