### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by Kore-Development** [Spicord/Spicord#17]
I haven't had time yet to test out Spicord but I was wondering if Spicord can send Minecraft to Discord messages through webhooks like this.
![Screenshot_20201101-095916](https://user-images.githubusercontent.com/29719362/97807967-70677f80-1c29-11eb-926a-c234148a2bd1.png)

**Comment by OopsieWoopsie** [comment]
I didn't implemented that for Spicord itself but it uses JDA so I think you can do that by using purely JDA
