### ISSUE TITLE
Spicord Error in Console

### ISSUE THREAD

**Issue by ctrsl** [Spicord/Spicord#18]
Found this error when using /sp restart in the Proxy Console

`05.11 19:37:30 [Server] INFO [ERROR] Got an unexpected error. Please redirect following message to the devs:
05.11 19:37:30 [Server] INFO GUILD_CREATE -> {}`

Here is my config.toml

`# +--------------------------------------------------+
# | Project: Spicord                                 |
# | GitHub: https://github.com/OopsieWoopsie/Spicord |
# +--------------------------------------------------+

config_version = 1

[[bots]]
  name = "Cloudcraft Bot"
  enabled = true
  token = "NzEzMjU3NTc3NzQ3NTc4OTUz.Xsde4g.1mFeHzwYw58BNzpDPdofsqVIzh0"
  command_support = true
  command_prefix = "-"
  addons = [
    "spicord::info",
    "spicord::plugins",
    "spicord::players",
	"ban_announcer"
  ]
#[[bots]]
#  name = "another-bot"
#  enabled = false
#  token = "YOUR BOT TOKEN HERE"
#  command_support = true
#  command_prefix = "!"
#  addons = []

[jda_messages]
  enabled = true
  debug = false`

I'm using 1.15.2 backend version, and this plugin used to work but I moved the punishment log channel for BanAnnouncer and it's nor working anymore.

**Comment by OopsieWoopsie** [comment]
Closed because of #19
