### ISSUE TITLE
GUILD_CREATE Error

### ISSUE THREAD

**Issue by ctrsl** [Spicord/Spicord#19]
Found this error when using /sp restart in the Proxy Console

```
05.11 19:37:30 [Server] INFO [ERROR] Got an unexpected error. Please redirect following message to the devs:
05.11 19:37:30 [Server] INFO GUILD_CREATE -> {}
```

Here is my config.toml

```
[[bots]]
  name = "Cloudcraft Bot"
  enabled = true
  token = "REMOVED BECAUSE YOU POSTED IT"
  command_support = true
  command_prefix = "-"
  addons = [
    "spicord::info",
    "spicord::plugins",
    "spicord::players",
	"ban_announcer"
```

I'm using 1.15.2 backend version, and this plugin used to work but I moved the punishment log channel for BanAnnouncer and it's nor working anymore.

**Comment by OopsieWoopsie** [comment]
I had to edit your message and remove the history because you included your bot token, go to the Discord Developer Portal ( https://discord.com/developers/applications ) and regenerate it, and never post your token again since someone can use it **TO DESTROY YOUR DISCORD SERVER**!
----
Please send me a full and clean startup log of your server, since you start it until Spicord finishes loading.

**Comment by ctrsl** [comment]
Ok, do you have Discord so contacting is easier?

**Comment by ctrsl** [comment]
`06.11 00:34:33 [Multicraft] Starting server!
06.11 00:34:33 [Multicraft] Loaded config for "AUTO UPDATING: BungeeCord Latest (Current: #1539)"
06.11 00:34:34 [Multicraft] JAR file not found, copying from global JAR directory
06.11 00:34:34 [Multicraft] Updating eula.txt file
06.11 00:34:35 [Server] INFO Using mbed TLS based native cipher.
06.11 00:34:35 [Server] INFO Using zlib based native compressor.
06.11 00:34:35 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:9c078b7:1539
06.11 00:34:35 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
06.11 00:34:35 [Server] INFO Epoll is working, utilising it!
06.11 00:34:35 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
06.11 00:34:35 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
06.11 00:34:35 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
06.11 00:34:35 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
06.11 00:34:35 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
06.11 00:34:35 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
06.11 00:34:35 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:35 [Server] INFO Loaded plugin LuckPerms version 5.1.4 by Luck
06.11 00:34:35 [Server] INFO Loaded plugin AdvancedPortals version 0.5.4 by sekwah41
06.11 00:34:35 [Server] WARNING Error enabling plugin Playtime
06.11 00:34:35 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
06.11 00:34:35 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method)
06.11 00:34:35 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
06.11 00:34:35 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
06.11 00:34:35 [Server] INFO at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
06.11 00:34:35 [Server] INFO at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
06.11 00:34:35 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
06.11 00:34:35 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
06.11 00:34:35 [Server] INFO at java.security.AccessController.doPrivileged(Native Method)
06.11 00:34:35 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
06.11 00:34:35 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
06.11 00:34:35 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:44)
06.11 00:34:35 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
06.11 00:34:35 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
06.11 00:34:35 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:327)
06.11 00:34:35 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:235)
06.11 00:34:35 [Server] INFO at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
06.11 00:34:35 [Server] INFO at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
06.11 00:34:35 [Server] INFO at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
06.11 00:34:35 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
06.11 00:34:35 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63)
06.11 00:34:35 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
06.11 00:34:35 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
06.11 00:34:35 [Server] INFO ... 18 more
06.11 00:34:35 [Server] INFO Loaded plugin NuVotifier version 2.7.1 by Ichbinjoe, blakeman8192, Kramer, tuxed
06.11 00:34:35 [Server] INFO Loaded plugin cmd_list version git:cmd_list:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:35 [Server] INFO Loaded plugin Spicord version 2.6.0-SNAPSHOT by OopsieWoopsie
06.11 00:34:35 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:35 [Server] INFO Loaded plugin AdvancedBan version 2.1.9 by Leoko
06.11 00:34:36 [Server] INFO Loaded plugin ViaVersion version 3.1.1 by _MylesC, creeper123123321, Gerrygames, KennyTV, Matsv
06.11 00:34:36 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:36 [Server] INFO Loaded plugin UltraStaffChat version 3.0.0 by JoshuaSing
06.11 00:34:36 [Server] INFO Loaded plugin BanAnnouncer version 2.0.1 by OopsieWoopsie
06.11 00:34:36 [Server] INFO Loaded plugin BuycraftX version 12.0.6 by Buycraft
06.11 00:34:36 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:36 [Server] INFO Loaded plugin ServerListPlus version 3.4.8 by Minecrell <https://github.com/Minecrell>
06.11 00:34:36 [Server] INFO Loaded plugin cmd_send version git:cmd_send:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:36 [Server] WARNING Error enabling plugin ProtocolLib
06.11 00:34:36 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
06.11 00:34:36 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method)
06.11 00:34:36 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
06.11 00:34:36 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
06.11 00:34:36 [Server] INFO at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
06.11 00:34:36 [Server] INFO at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
06.11 00:34:36 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
06.11 00:34:36 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
06.11 00:34:36 [Server] INFO at java.security.AccessController.doPrivileged(Native Method)
06.11 00:34:36 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
06.11 00:34:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
06.11 00:34:36 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:44)
06.11 00:34:36 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
06.11 00:34:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
06.11 00:34:36 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:327)
06.11 00:34:36 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:235)
06.11 00:34:36 [Server] INFO at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
06.11 00:34:36 [Server] INFO at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
06.11 00:34:36 [Server] INFO at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
06.11 00:34:36 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
06.11 00:34:36 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63)
06.11 00:34:36 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37)
06.11 00:34:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
06.11 00:34:36 [Server] INFO ... 18 more
06.11 00:34:36 [Server] WARNING Forced host server pvp is not defined
06.11 00:34:36 [Server] INFO Enabled plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:36 [Server] INFO __    
06.11 00:34:36 [Server] INFO |    |__)   LuckPerms v5.1.4
06.11 00:34:36 [Server] INFO |___ |      Running on BungeeCord - BungeeCord
06.11 00:34:36 [Server] INFO Loading configuration...
06.11 00:34:36 [Server] INFO Loading storage provider... [MYSQL]
06.11 00:34:36 [Server] SEVERE INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Starting...
06.11 00:34:36 [Server] SEVERE INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Start completed.
06.11 00:34:37 [Server] INFO Loading messaging service... [SQL]
06.11 00:34:37 [Server] INFO Loading internal permission managers...
06.11 00:34:37 [Server] INFO Performing initial data load...
06.11 00:34:37 [Server] INFO Successfully enabled. (took 1624ms)
06.11 00:34:37 [Server] INFO Enabled plugin LuckPerms version 5.1.4 by Luck
06.11 00:34:37 [Server] INFO Advanced portals have been successfully enabled!
06.11 00:34:37 [Server] INFO Enabled plugin AdvancedPortals version 0.5.4 by sekwah41
06.11 00:34:37 [Server] INFO Loaded token for website: default
06.11 00:34:37 [Server] INFO Using epoll transport to accept votes.
06.11 00:34:37 [Server] INFO Forwarding votes from this NuVotifier instance to another NuVotifier server.
06.11 00:34:37 [Server] INFO Votifier enabled on socket /0:0:0:0:0:0:0:0%0:7959.
06.11 00:34:37 [Server] INFO Enabled plugin NuVotifier version 2.7.1 by Ichbinjoe, blakeman8192, Kramer, tuxed
06.11 00:34:37 [Server] INFO Enabled plugin cmd_list version git:cmd_list:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:37 [Server] INFO Enabled plugin Spicord version 2.6.0-SNAPSHOT by OopsieWoopsie
06.11 00:34:37 [Server] INFO Enabled plugin cmd_find version git:cmd_find:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:38 [Server] SEVERE INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
06.11 00:34:38 [Server] SEVERE INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
06.11 00:34:38 [Server] INFO []=====[Enabling AdvancedBan]=====[]
06.11 00:34:38 [Server] INFO | Information:
06.11 00:34:38 [Server] INFO |   Name: AdvancedBan
06.11 00:34:38 [Server] INFO |   Developer: Leoko
06.11 00:34:38 [Server] INFO |   Version: 2.1.9
06.11 00:34:38 [Server] INFO |   Storage: MySQL (external)
06.11 00:34:38 [Server] INFO | Support:
06.11 00:34:38 [Server] INFO |   Github: https://github.com/DevLeoko/AdvancedBan/issues
06.11 00:34:38 [Server] INFO |   Discord: https://discord.gg/ycDG6rS
06.11 00:34:38 [Server] INFO | Twitter: @LeokoGar
06.11 00:34:38 [Server] INFO | Update:
06.11 00:34:38 [Server] INFO |   There is a new version available! [2.3.0]
06.11 00:34:38 [Server] INFO []================================[]
06.11 00:34:38 [Server] INFO Enabled plugin AdvancedBan version 2.1.9 by Leoko
06.11 00:34:38 [Server] INFO Loading 1.12.2 -> 1.13 mappings...
06.11 00:34:38 [Server] INFO Loading 1.13.2 -> 1.14 mappings...
06.11 00:34:38 [Server] INFO Loading 1.14.4 -> 1.15 mappings...
06.11 00:34:38 [Server] INFO Loading 1.15 -> 1.16 mappings...
06.11 00:34:39 [Server] INFO Loading 1.16.1 -> 1.16.2 mappings...
06.11 00:34:39 [Server] WARNING There is a newer version available: 3.2.0, you're on: 3.1.1
06.11 00:34:39 [Server] INFO Plugin Starting...
06.11 00:34:39 [Server] INFO Enabled plugin ViaVersion version 3.1.1 by _MylesC, creeper123123321, Gerrygames, KennyTV, Matsv
06.11 00:34:39 [Server] INFO Enabled plugin cmd_server version git:cmd_server:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:39 [Server] INFO ViaVersion detected server version: 1.8.x(47)
06.11 00:34:39 [Server] INFO Enabled plugin UltraStaffChat version 3.0.0 by JoshuaSing
06.11 00:34:39 [Server] INFO Registered addon 'Ban Announcer' (ban_announcer) by OopsieWoopsie
06.11 00:34:39 [Server] INFO The pĺugin will start in 5 seconds...
06.11 00:34:39 [Server] INFO Enabled plugin BanAnnouncer version 2.0.1 by OopsieWoopsie
06.11 00:34:39 [Server] INFO Validating your server key...
06.11 00:34:39 [Server] INFO Loading block connection mappings ...
06.11 00:34:40 [Server] INFO Enabled plugin BuycraftX version 12.0.6 by Buycraft
06.11 00:34:40 [Server] INFO Enabled plugin cmd_alert version git:cmd_alert:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:40 [Server] INFO [Core] Reloading configuration...
06.11 00:34:40 [Server] INFO [Core] Loaded configuration: ServerStatusConf
06.11 00:34:40 [Server] INFO [Core] Loaded configuration: PluginConf
06.11 00:34:40 [Server] INFO [Core] Reloading saved player identities...
06.11 00:34:40 [Server] INFO Successfully loaded!
06.11 00:34:40 [Server] INFO Enabled plugin ServerListPlus version 3.4.8 by Minecrell <https://github.com/Minecrell>
06.11 00:34:40 [Server] INFO Enabled plugin cmd_send version git:cmd_send:1.16-R0.4-SNAPSHOT:9c078b7:1539 by SpigotMC
06.11 00:34:40 [Server] Startup Listening on /192.99.221.226:25565
06.11 00:34:41 [Server] INFO Fetching all due players...
06.11 00:34:41 [Server] INFO Fetched due players (0 found).
06.11 00:34:44 [Server] INFO ##  ## ###### ###### 
06.11 00:34:44 [Server] INFO ##  ## ##     ##     UltraStaffChat v3.0.0
06.11 00:34:44 [Server] INFO ##  ## ###### ##     Copyright 2019 Joshua Sing.
06.11 00:34:44 [Server] INFO ##  ##     ## ##     Running on Bungeecord v1.8.x-1.16.x
06.11 00:34:44 [Server] INFO ###### ###### ###### 
06.11 00:34:44 [Server] INFO [AutoDetect] Using AdvancedBan as the punishment manager.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'annotations-16.0.1.jar'.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'jsr305-3.0.2.jar'.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'commons-collections4-4.1.jar'.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'jna-4.4.0.jar'.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'json-20160810.jar'.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'nv-websocket-client-2.5.jar'.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'okio-2.2.2.jar'.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'okhttp-3.13.0.jar'.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'opus-java-api-1.0.4.jar'.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'opus-java-natives-1.0.4.jar'.
06.11 00:34:48 [Server] INFO [Loader] The library 'net.sf.trove4j:trove4j:3.0.3' wasn't loaded by Spicord, errors may occur.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'kotlin-stdlib-1.3.31.jar'.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'toml4j-0.7.2.jar'.
06.11 00:34:48 [Server] INFO [Loader] Loaded library 'JDA-3.8.3-mcdb.jar'.
06.11 00:34:48 [Server] INFO Loaded 1 bots, 0 disabled.
06.11 00:34:48 [Server] INFO Registered addon 'Server Information' (spicord::info) by OopsieWoopsie
06.11 00:34:48 [Server] INFO Registered addon 'Plugin List' (spicord::plugins) by OopsieWoopsie
06.11 00:34:48 [Server] INFO Registered addon 'Player List' (spicord::players) by OopsieWoopsie
06.11 00:34:48 [Server] INFO Starting the bots...
06.11 00:34:48 [Server] INFO Starting bot 'Cloudcraft Bot'.
06.11 00:34:48 [Server] INFO [INFO] Login Successful!
06.11 00:34:48 [Server] INFO [INFO] Connected to WebSocket
06.11 00:34:49 [Server] INFO [ERROR] Got an unexpected error. Please redirect following message to the devs:
06.11 00:34:49 [Server] INFO GUILD_CREATE -> {}`

There is the console

**Comment by ctrsl** [comment]
https://hastebin.com/kumujekaku.yaml There is a fresh Console start up

**Comment by OopsieWoopsie** [comment]
Before reporting issues make sure to use the latest plugin version, the latest (and only working) Spicord version is now 3.1.1/3.1.2, you are using 2.6.0 which is **very old.**
https://github.com/Spicord/Spicord/releases/tag/3.1.2-dev
