### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by dramasailor** [Spicord/Spicord#23]
We're trying to run Spicord 3.1.2 with Ban Announcer, and even with the bot disabled in config.toml, we're getting a flood of errors on the Bungee console of:

`[01:31:04 INFO] [Spicord]: Registered addon 'Server Information' (spicord::info) by Sheidy
[01:31:04 INFO] [Spicord]: Registered addon 'Plugin List' (spicord::plugins) by Sheidy
[01:31:04 INFO] [Spicord]: Registered addon 'Player List' (spicord::players) by Sheidy
[01:31:04 INFO] [Spicord]: Starting the bots...
[01:31:04 INFO] [Spicord]: Starting bot 'ban announcer'.
[01:31:04 INFO]: Spicord has been restarted!
=>.... [01:31:04 INFO] [Spicord]: [JDA:JDA] Login Successful!
>.... [01:31:05 INFO] [Spicord]: [JDA:WebSocketClient] Connected to WebSocket
>.... [01:31:05 WARN] [Spicord]: [JDA:WebSocketClient] WebSocket connection closed with unknown meaning for close-code 4014
>.... [01:31:05 ERROR] [Spicord]: [JDA:WebSocketClient] Encountered IDENTIFY Rate Limit!
>.... [01:31:05 WARN] [Spicord]: [JDA:WebSocketClient] Got disconnected from WebSocket. Appending to reconnect queue`

The last four lines then repeat on loop every 6-8 seconds. 

Any other information I can provide, please let me know.

**Comment by OopsieWoopsie** [comment]
Read the big red text in the first line of the [SpigotMC page](https://www.spigotmc.org/resources/spicord.64918/)
