### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aril3721** [Spicord/Spicord#25]
Hello. How i can Make Custom Command Like (prefix)tps and showing 20.00 Tps

Sorry for my english. im not good on english language :(

**Comment by OopsieWoopsie** [comment]
Hi, in the case you know how to program in Java, then a can guide you, otherwise I can't :(
Do you know how to program?

**Comment by aril3721** [comment]
> Hi, in the case you know how to program in Java, then a can guide you, otherwise I can't :(
> Do you know how to program?

no :( but if it simple maybe i can :D

**Comment by OopsieWoopsie** [comment]
If you don't have any programming experience then sadly there's nothing "simple" :(

**Comment by aril3721** [comment]
':(

**Comment by aril3721** [comment]
But. Can you make a tutorial?? I search it on youtube google but no found anything

**Comment by OopsieWoopsie** [comment]
Make a tutorial about what? About how to program in Java then to learn the Bukkit api then how to code anything you want? I'm sorry but I don't have +200 hours of free time... it is not easy to teach even the basic stuff, it isn't something that can be done in an hour or so, sorry.

**Comment by aril3721** [comment]
:'( ok
