### ISSUE TITLE
Encountered IDENTIFY Rate Limit!

### ISSUE THREAD

**Issue by MrCoderrrrrrr** [Spicord/Spicord#26]
Hello, when I add my bot token it says this:
`[Spicord]: [JDA:WebSocketClient] Encountered IDENTIFY Rate Limit!`

It spams requests until Discord changes my bot token because they think I got hacked.
Can someone help me?

**Comment by OopsieWoopsie** [comment]
Have you followed what the **big red text** in the **first line** of the SpigotMC [post](https://www.spigotmc.org/resources/spicord.64918/) says?
