### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by squeaky2137** [Spicord/Spicord#28]
Issue
[Wed, 20. Jan 2021 13:38:06 GMT WARN] [JDA:WebSocketClient] Got an unexpected Json-parse error. Please redirect following message to the devs:
	JSONObject["embeds"] not found.
	MESSAGE\_UPDATE -> {"flags":1,"guild\_id":"783710068049969182","id":"801444737088749629","channel\_id":"785708573682171924"}

**Comment by OopsieWoopsie** [comment]
Reopened because I didn't released a fix yet. (I already know what is causing this)

**Comment by squeaky2137** [comment]
Kk

**Comment by OopsieWoopsie** [comment]
Closed because Spicord now uses JDA 4.2.1 since a long time ago.
