### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by JBCDev39** [Spicord/Spicord#34]
I get this every time I restart the server, and I do not really know how to fix it. The [ERROR]

00:43:02 INFO]: [Spicord] Starting the bots...
[00:43:02 INFO]: [Spicord] Starting bot 'default'.
[00:43:02 INFO]: [Spicord] [JDA:JDA] Login Successful!
[00:43:02 INFO]: [Spicord] [JDA:WebSocketClient] Connected to WebSocket
[00:43:02 ERROR]: [Spicord] [JDA:EntityBuilder] Cannot create channel for type 13
[00:43:02 INFO]: [Spicord] [JDA:JDA] Finished Loading!

**Comment by OopsieWoopsie** [comment]
Hi, that's because you have an ["Stage Channel"](https://blog.discord.com/captivate-your-community-with-stage-channels-46bbb756e89b)

Does that error makes Spicord to don't work?

**Comment by JBCDev39** [comment]
No, the plugin is completely functional.

**Comment by OopsieWoopsie** [comment]
Okay, that's good to know.
I will look at this when I have some free time, thanks for reporting the issue.

**Comment by JBCDev39** [comment]
Ok thanks, appreciate the quick response.

**Comment by mahtio** [comment]
I'm in the same situation here, but it's working too!!

**Comment by OopsieWoopsie** [comment]
@mahtio 
This should not happen on the latest Spicord version (4)
