### ISSUE TITLE
Issue, please help

### ISSUE THREAD

**Issue by VultarexCZ** [Spicord/Spicord#35]
Issue:
22:26:28[INFO] [Spicord] [JDA:WebSocketClient] Connected to WebSocket
22:26:28[WARN] [Spicord] [JDA:WebSocketClient] WebSocket connection closed with unknown meaning for close-code 4014
22:26:28[ERROR] [Spicord] [JDA:WebSocketClient] Encountered IDENTIFY Rate Limit!
22:26:28[WARN] [Spicord] [JDA:WebSocketClient] Got disconnected from WebSocket. Appending to reconnect queue

**Comment by VultarexCZ** [comment]
Config:

[[bots]]
  name = "XXX"
  enabled = true
  token = "XXX"
  command_support = true
  command_prefix = "-"
  addons = [
    "spicord::info",
    "spicord::plugins",
    "spicord::players"
  ]

**Comment by OopsieWoopsie** [comment]
Read the **first line** on the spigotmc post, you will see some big red letters being pointed with arrows, just... read that.
