### ISSUE TITLE
Startup Warning

### ISSUE THREAD

**Issue by JBCDev39** [Spicord/Spicord#36]
Hello, I am running the server on PaperMC 1.16.5-b629 (Java 11). I just updated to Java 11 actually. Now I get this on console. The plugin is functional btw.

> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.spicord.reflect.ReflectedMethod (file:/home/minecraft/servers/user/plugins/Spicord_3.1.4.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.spicord.reflect.ReflectedMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by OopsieWoopsie** [comment]
Hello! this warning should not appear anymore on version 3.1.5

https://github.com/Spicord/Spicord/releases/tag/3.1.5
