### ISSUE TITLE
[Question] Discord Status

### ISSUE THREAD

**Issue by athkiasaris1** [Spicord/Spicord#38]
I was wondering if I could change the status of the discord bot with the api but I dont know if it is possible.

**Comment by OopsieWoopsie** [comment]
Hi, there's already an addon for that: https://github.com/OopsieWoopsie/DiscordMOTD
For using it you need to:
1. Download the DiscordMOTD.sp file: https://github.com/OopsieWoopsie/DiscordMOTD/releases/tag/test
2. Place the file into the `plugins > Spicord > addons` folder
3. Add "motd" into your bot addons list (`plugins > Spicord > config.toml`)
4. Restart you server, if you don't want to do that then just run `/sp restart` to restart Spicord.

Your bot will then change its status to the preconfigured ones each 30 seconds.

If you want to change them, open the folder called "DiscordMOTD" that got automatically created into the "addons" folder, open the file config.yml file and set your custom statuses, don't forget to restart again for the changes to take effect.

**Comment by maciejkamo20** [comment]
It doesnt work anymore

**Comment by bijsven** [comment]
yeah
