### ISSUE TITLE
How I Can Send Message To Spesific Channel?

### ISSUE THREAD

**Issue by aril3721** [Spicord/Spicord#50]
Sorry I Write This In GitHub. I Searching For Discord Support But Not Found Anything.

Soo How I Can Do That

**Comment by OopsieWoopsie** [comment]
I don't understand what do you mean, please explain further.
Spicord can't send messages by itself, you need an addon for that.

**Comment by aril3721** [comment]
> I don't understand what do you mean, please explain further. Spicord can't send messages by itself, you need an addon for that.

Soo. I want to create spicord addons for my plugin. For example. If player join sending a message to spesific channel. I did not found an wiki for that. Thats why i need help in here. 

I'm sry for my english

**Comment by OopsieWoopsie** [comment]
> Soo. I want to create spicord addons for my plugin. For example. If player join sending a message to spesific channel. I did not found an wiki for that. Thats why i need help in here.
> 
> Example: Me Join And Spicord (addons) send message to my discord with spesific channel

There ins't any addon that does that actually, but here's something similar, it an Spicord addon made in JavaScript, it's called ChatSync:
https://github.com/OopsieWoopsie/ChatSync/
It sends all player chat messages to Discord. In case you want to use it, you need to download the `ChatSync.sp` file located in that url, and put it into the `plugins/Spicord/addons` folder, when you start the server the configuration file for that addon will be created in `plugins/Spicord/addons/ChatSync/config.yml`

> I'm sry for my english

I also speak portuguese and spanish in case you speak any of these.

**Comment by aril3721** [comment]
oh thanks Man :D. but can you make discord for support. its make me confused
